services:
  - type: web
    name: calculator-web-expert
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn freight_quote.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: calculatorwebexpert.onrender.com,calculator-web-expert.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://calculatorwebexpert.onrender.com,https://calculator-web-expert.onrender.com
      - key: SECRET_KEY
        generateValue: true
