# Country aliases for normalization (legacy -> canonical Spanish names).
COUNTRY_CODE_TO_NAME = {
    "AD": "Andorra",
    "AE": "Emiratos Árabes Unidos",
    "AF": "Afganistán",
    "AG": "Antigua y Barbuda",
    "AI": "Anguila",
    "AL": "Albania",
    "AM": "Armenia",
    "AO": "Angola",
    "AQ": "Antártida",
    "AR": "Argentina",
    "AS": "Samoa Americana",
    "AT": "Austria",
    "AU": "Australia",
    "AW": "Aruba",
    "AX": "Islas Aland",
    "AZ": "Azerbaiyán",
    "BA": "Bosnia y Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladés",
    "BE": "Bélgica",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Baréin",
    "BI": "Burundi",
    "BJ": "Benín",
    "BL": "San Bartolomé",
    "BM": "Bermudas",
    "BN": "Brunéi",
    "BO": "Bolivia",
    "BQ": "Caribe neerlandés",
    "BR": "Brasil",
    "BS": "Bahamas",
    "BT": "Bután",
    "BV": "Isla Bouvet",
    "BW": "Botsuana",
    "BY": "Bielorrusia",
    "BZ": "Belice",
    "CA": "Canadá",
    "CC": "Islas Cocos",
    "CD": "República Democrática del Congo",
    "CF": "República Centroafricana",
    "CG": "Congo",
    "CH": "Suiza",
    "CI": "Côte d’Ivoire",
    "CK": "Islas Cook",
    "CL": "Chile",
    "CM": "Camerún",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CW": "Curazao",
    "CX": "Isla de Navidad",
    "CY": "Chipre",
    "CZ": "Chequia",
    "DE": "Alemania",
    "DJ": "Yibuti",
    "DK": "Dinamarca",
    "DM": "Dominica",
    "DO": "República Dominicana",
    "DZ": "Argelia",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egipto",
    "EH": "Sáhara Occidental",
    "ER": "Eritrea",
    "ES": "España",
    "ET": "Etiopía",
    "FI": "Finlandia",
    "FJ": "Fiyi",
    "FK": "Islas Malvinas",
    "FM": "Micronesia",
    "FO": "Islas Feroe",
    "FR": "Francia",
    "GA": "Gabón",
    "GB": "Reino Unido",
    "GD": "Granada",
    "GE": "Georgia",
    "GF": "Guayana Francesa",
    "GG": "Guernesey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Groenlandia",
    "GM": "Gambia",
    "GN": "Guinea",
    "GP": "Guadalupe",
    "GQ": "Guinea Ecuatorial",
    "GR": "Grecia",
    "GS": "Islas Georgia del Sur y Sandwich del Sur",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinea-Bisáu",
    "GY": "Guyana",
    "HK": "RAE de Hong Kong (China)",
    "HM": "Islas Heard y McDonald",
    "HN": "Honduras",
    "HR": "Croacia",
    "HT": "Haití",
    "HU": "Hungría",
    "ID": "Indonesia",
    "IE": "Irlanda",
    "IL": "Israel",
    "IM": "Isla de Man",
    "IN": "India",
    "IO": "Territorio Británico del Océano Índico",
    "IQ": "Irak",
    "IR": "Irán",
    "IS": "Islandia",
    "IT": "Italia",
    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "Jordania",
    "JP": "Japón",
    "KE": "Kenia",
    "KG": "Kirguistán",
    "KH": "Camboya",
    "KI": "Kiribati",
    "KM": "Comoras",
    "KN": "San Cristóbal y Nieves",
    "KP": "Corea del Norte",
    "KR": "Corea del Sur",
    "KW": "Kuwait",
    "KY": "Islas Caimán",
    "KZ": "Kazajistán",
    "LA": "Laos",
    "LB": "Líbano",
    "LC": "Santa Lucía",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesoto",
    "LT": "Lituania",
    "LU": "Luxemburgo",
    "LV": "Letonia",
    "LY": "Libia",
    "MA": "Marruecos",
    "MC": "Mónaco",
    "MD": "Moldavia",
    "ME": "Montenegro",
    "MF": "San Martín",
    "MG": "Madagascar",
    "MH": "Islas Marshall",
    "MK": "Macedonia del Norte",
    "ML": "Mali",
    "MM": "Myanmar (Birmania)",
    "MN": "Mongolia",
    "MO": "RAE de Macao (China)",
    "MP": "Islas Marianas del Norte",
    "MQ": "Martinica",
    "MR": "Mauritania",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Mauricio",
    "MV": "Maldivas",
    "MW": "Malaui",
    "MX": "México",
    "MY": "Malasia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NC": "Nueva Caledonia",
    "NE": "Níger",
    "NF": "Isla Norfolk",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Países Bajos",
    "NO": "Noruega",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "Nueva Zelanda",
    "OM": "Omán",
    "PA": "Panamá",
    "PE": "Perú",
    "PF": "Polinesia Francesa",
    "PG": "Papúa Nueva Guinea",
    "PH": "Filipinas",
    "PK": "Pakistán",
    "PL": "Polonia",
    "PM": "San Pedro y Miquelón",
    "PN": "Islas Pitcairn",
    "PR": "Puerto Rico",
    "PS": "Territorios Palestinos",
    "PT": "Portugal",
    "PW": "Palaos",
    "PY": "Paraguay",
    "QA": "Catar",
    "RE": "Reunión",
    "RO": "Rumanía",
    "RS": "Serbia",
    "RU": "Rusia",
    "RW": "Ruanda",
    "SA": "Arabia Saudí",
    "SB": "Islas Salomón",
    "SC": "Seychelles",
    "SD": "Sudán",
    "SE": "Suecia",
    "SG": "Singapur",
    "SH": "Santa Elena",
    "SI": "Eslovenia",
    "SJ": "Svalbard y Jan Mayen",
    "SK": "Eslovaquia",
    "SL": "Sierra Leona",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Surinam",
    "SS": "Sudán del Sur",
    "ST": "Santo Tomé y Príncipe",
    "SV": "El Salvador",
    "SX": "Sint Maarten",
    "SY": "Siria",
    "SZ": "Esuatini",
    "TC": "Islas Turcas y Caicos",
    "TD": "Chad",
    "TF": "Territorios Australes Franceses",
    "TG": "Togo",
    "TH": "Tailandia",
    "TJ": "Tayikistán",
    "TK": "Tokelau",
    "TL": "Timor-Leste",
    "TM": "Turkmenistán",
    "TN": "Túnez",
    "TO": "Tonga",
    "TR": "Turquía",
    "TT": "Trinidad y Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwán",
    "TZ": "Tanzania",
    "UA": "Ucrania",
    "UG": "Uganda",
    "UM": "Islas menores alejadas de EE. UU.",
    "US": "Estados Unidos",
    "UY": "Uruguay",
    "UZ": "Uzbekistán",
    "VA": "Ciudad del Vaticano",
    "VC": "San Vicente y las Granadinas",
    "VE": "Venezuela",
    "VG": "Islas Vírgenes Británicas",
    "VI": "Islas Vírgenes de EE. UU.",
    "VN": "Vietnam",
    "VU": "Vanuatu",
    "WF": "Wallis y Futuna",
    "WS": "Samoa",
    "YE": "Yemen",
    "YT": "Mayotte",
    "ZA": "Sudáfrica",
    "ZM": "Zambia",
    "ZW": "Zimbabue",
}

COUNTRY_ENGLISH_TO_NAME = {
    "afghanistan": "Afganistán",
    "albania": "Albania",
    "algeria": "Argelia",
    "andorra": "Andorra",
    "angola": "Angola",
    "anguilla": "Anguila",
    "antarctica": "Antártida",
    "antigua & barbuda": "Antigua y Barbuda",
    "argentina": "Argentina",
    "armenia": "Armenia",
    "aruba": "Aruba",
    "australia": "Australia",
    "austria": "Austria",
    "azerbaijan": "Azerbaiyán",
    "bahamas": "Bahamas",
    "bahrain": "Baréin",
    "bangladesh": "Bangladés",
    "barbados": "Barbados",
    "belarus": "Bielorrusia",
    "belgium": "Bélgica",
    "belize": "Belice",
    "benin": "Benín",
    "bermuda": "Bermudas",
    "bhutan": "Bután",
    "bolivia": "Bolivia",
    "bosnia & herzegovina": "Bosnia y Herzegovina",
    "botswana": "Botsuana",
    "bouvet island": "Isla Bouvet",
    "brazil": "Brasil",
    "britain (uk)": "Reino Unido",
    "british indian ocean territory": "Territorio Británico del Océano Índico",
    "brunei": "Brunéi",
    "bulgaria": "Bulgaria",
    "burkina faso": "Burkina Faso",
    "burundi": "Burundi",
    "cambodia": "Camboya",
    "cameroon": "Camerún",
    "canada": "Canadá",
    "cape verde": "Cabo Verde",
    "caribbean nl": "Caribe neerlandés",
    "cayman islands": "Islas Caimán",
    "central african rep.": "República Centroafricana",
    "chad": "Chad",
    "chile": "Chile",
    "china": "China",
    "christmas island": "Isla de Navidad",
    "cocos (keeling) islands": "Islas Cocos",
    "colombia": "Colombia",
    "comoros": "Comoras",
    "congo (dem. rep.)": "República Democrática del Congo",
    "congo (rep.)": "Congo",
    "cook islands": "Islas Cook",
    "costa rica": "Costa Rica",
    "croatia": "Croacia",
    "cuba": "Cuba",
    "curaçao": "Curazao",
    "cyprus": "Chipre",
    "czech republic": "Chequia",
    "côte d'ivoire": "Côte d’Ivoire",
    "denmark": "Dinamarca",
    "djibouti": "Yibuti",
    "dominica": "Dominica",
    "dominican republic": "República Dominicana",
    "east timor": "Timor-Leste",
    "ecuador": "Ecuador",
    "egypt": "Egipto",
    "el salvador": "El Salvador",
    "equatorial guinea": "Guinea Ecuatorial",
    "eritrea": "Eritrea",
    "estonia": "Estonia",
    "eswatini (swaziland)": "Esuatini",
    "ethiopia": "Etiopía",
    "falkland islands": "Islas Malvinas",
    "faroe islands": "Islas Feroe",
    "fiji": "Fiyi",
    "finland": "Finlandia",
    "france": "Francia",
    "french guiana": "Guayana Francesa",
    "french polynesia": "Polinesia Francesa",
    "french s. terr.": "Territorios Australes Franceses",
    "gabon": "Gabón",
    "gambia": "Gambia",
    "georgia": "Georgia",
    "germany": "Alemania",
    "ghana": "Ghana",
    "gibraltar": "Gibraltar",
    "greece": "Grecia",
    "greenland": "Groenlandia",
    "grenada": "Granada",
    "guadeloupe": "Guadalupe",
    "guam": "Guam",
    "guatemala": "Guatemala",
    "guernsey": "Guernesey",
    "guinea": "Guinea",
    "guinea-bissau": "Guinea-Bisáu",
    "guyana": "Guyana",
    "haiti": "Haití",
    "heard island & mcdonald islands": "Islas Heard y McDonald",
    "honduras": "Honduras",
    "hong kong": "RAE de Hong Kong (China)",
    "hungary": "Hungría",
    "iceland": "Islandia",
    "india": "India",
    "indonesia": "Indonesia",
    "iran": "Irán",
    "iraq": "Irak",
    "ireland": "Irlanda",
    "isle of man": "Isla de Man",
    "israel": "Israel",
    "italy": "Italia",
    "jamaica": "Jamaica",
    "japan": "Japón",
    "jersey": "Jersey",
    "jordan": "Jordania",
    "kazakhstan": "Kazajistán",
    "kenya": "Kenia",
    "kiribati": "Kiribati",
    "korea (north)": "Corea del Norte",
    "korea (south)": "Corea del Sur",
    "kuwait": "Kuwait",
    "kyrgyzstan": "Kirguistán",
    "laos": "Laos",
    "latvia": "Letonia",
    "lebanon": "Líbano",
    "lesotho": "Lesoto",
    "liberia": "Liberia",
    "libya": "Libia",
    "liechtenstein": "Liechtenstein",
    "lithuania": "Lituania",
    "luxembourg": "Luxemburgo",
    "macau": "RAE de Macao (China)",
    "madagascar": "Madagascar",
    "malawi": "Malaui",
    "malaysia": "Malasia",
    "maldives": "Maldivas",
    "mali": "Mali",
    "malta": "Malta",
    "marshall islands": "Islas Marshall",
    "martinique": "Martinica",
    "mauritania": "Mauritania",
    "mauritius": "Mauricio",
    "mayotte": "Mayotte",
    "mexico": "México",
    "micronesia": "Micronesia",
    "moldova": "Moldavia",
    "monaco": "Mónaco",
    "mongolia": "Mongolia",
    "montenegro": "Montenegro",
    "montserrat": "Montserrat",
    "morocco": "Marruecos",
    "mozambique": "Mozambique",
    "myanmar (burma)": "Myanmar (Birmania)",
    "namibia": "Namibia",
    "nauru": "Nauru",
    "nepal": "Nepal",
    "netherlands": "Países Bajos",
    "new caledonia": "Nueva Caledonia",
    "new zealand": "Nueva Zelanda",
    "nicaragua": "Nicaragua",
    "niger": "Níger",
    "nigeria": "Nigeria",
    "niue": "Niue",
    "norfolk island": "Isla Norfolk",
    "north macedonia": "Macedonia del Norte",
    "northern mariana islands": "Islas Marianas del Norte",
    "norway": "Noruega",
    "oman": "Omán",
    "pakistan": "Pakistán",
    "palau": "Palaos",
    "palestine": "Territorios Palestinos",
    "panama": "Panamá",
    "papua new guinea": "Papúa Nueva Guinea",
    "paraguay": "Paraguay",
    "peru": "Perú",
    "philippines": "Filipinas",
    "pitcairn": "Islas Pitcairn",
    "poland": "Polonia",
    "portugal": "Portugal",
    "puerto rico": "Puerto Rico",
    "qatar": "Catar",
    "romania": "Rumanía",
    "russia": "Rusia",
    "rwanda": "Ruanda",
    "réunion": "Reunión",
    "samoa (american)": "Samoa Americana",
    "samoa (western)": "Samoa",
    "san marino": "San Marino",
    "sao tome & principe": "Santo Tomé y Príncipe",
    "saudi arabia": "Arabia Saudí",
    "senegal": "Senegal",
    "serbia": "Serbia",
    "seychelles": "Seychelles",
    "sierra leone": "Sierra Leona",
    "singapore": "Singapur",
    "slovakia": "Eslovaquia",
    "slovenia": "Eslovenia",
    "solomon islands": "Islas Salomón",
    "somalia": "Somalia",
    "south africa": "Sudáfrica",
    "south georgia & the south sandwich islands": "Islas Georgia del Sur y Sandwich del Sur",
    "south sudan": "Sudán del Sur",
    "spain": "España",
    "sri lanka": "Sri Lanka",
    "st barthelemy": "San Bartolomé",
    "st helena": "Santa Elena",
    "st kitts & nevis": "San Cristóbal y Nieves",
    "st lucia": "Santa Lucía",
    "st maarten (dutch)": "Sint Maarten",
    "st martin (french)": "San Martín",
    "st pierre & miquelon": "San Pedro y Miquelón",
    "st vincent": "San Vicente y las Granadinas",
    "sudan": "Sudán",
    "suriname": "Surinam",
    "svalbard & jan mayen": "Svalbard y Jan Mayen",
    "sweden": "Suecia",
    "switzerland": "Suiza",
    "syria": "Siria",
    "taiwan": "Taiwán",
    "tajikistan": "Tayikistán",
    "tanzania": "Tanzania",
    "thailand": "Tailandia",
    "togo": "Togo",
    "tokelau": "Tokelau",
    "tonga": "Tonga",
    "trinidad & tobago": "Trinidad y Tobago",
    "tunisia": "Túnez",
    "turkey": "Turquía",
    "turkmenistan": "Turkmenistán",
    "turks & caicos is": "Islas Turcas y Caicos",
    "tuvalu": "Tuvalu",
    "uganda": "Uganda",
    "ukraine": "Ucrania",
    "united arab emirates": "Emiratos Árabes Unidos",
    "united states": "Estados Unidos",
    "uruguay": "Uruguay",
    "us minor outlying islands": "Islas menores alejadas de EE. UU.",
    "uzbekistan": "Uzbekistán",
    "vanuatu": "Vanuatu",
    "vatican city": "Ciudad del Vaticano",
    "venezuela": "Venezuela",
    "vietnam": "Vietnam",
    "virgin islands (uk)": "Islas Vírgenes Británicas",
    "virgin islands (us)": "Islas Vírgenes de EE. UU.",
    "wallis & futuna": "Wallis y Futuna",
    "western sahara": "Sáhara Occidental",
    "yemen": "Yemen",
    "zambia": "Zambia",
    "zimbabwe": "Zimbabue",
    "åland islands": "Islas Aland",
}
