# Generated by Django 5.2.11 on 2026-02-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExchangeRate",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="total_cop",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="trm_usd_cop",
        ),
    ]
