# Generated by Django 5.2.11 on 2026-02-12 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_delete_exchangerate_remove_quote_total_cop_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FreightRateConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "air_rate_usd_per_kg",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "sea_rate_usd_per_m3",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "air_volumetric_factor",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_rate_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuracion de tarifas",
                "verbose_name_plural": "Configuracion de tarifas",
            },
        ),
    ]
