# Generated by Django 5.2.11 on 2026-02-12 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_freightrateconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=12, unique=True)),
                ("country", models.CharField(max_length=80)),
                (
                    "location_type",
                    models.CharField(
                        choices=[("AIRPORT", "Aeropuerto"), ("SEAPORT", "Puerto")],
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["location_type", "code"],
            },
        ),
        migrations.CreateModel(
            name="LocationRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usd_per_kg", models.DecimalField(decimal_places=4, max_digits=12)),
                ("usd_per_m3", models.DecimalField(decimal_places=4, max_digits=12)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_location_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="quotes.originlocation",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "-id"],
            },
        ),
        migrations.AddField(
            model_name="quote",
            name="applied_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="quotes.locationrate",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="origin_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotes",
                to="quotes.originlocation",
            ),
        ),
    ]
