# Generated by Django 5.2.11 on 2026-02-23 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0004_originlocation_locationrate_quote_applied_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="destination_country",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="quote",
            name="destination_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="destination_quotes",
                to="quotes.originlocation",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="origin_country",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
