# Generated by Codex on 2026-02-23

from django.db import migrations


def _normalize_country(raw: str, world_country_set: set[str], lower_lookup: dict[str, str], code_lookup: dict[str, str], english_lookup: dict[str, str]) -> str:
    if not raw:
        return raw
    value = str(raw).strip()
    if not value:
        return value

    if value in world_country_set:
        return value

    upper = value.upper()
    if upper in code_lookup and code_lookup[upper] in world_country_set:
        return code_lookup[upper]

    lower = value.lower()
    if lower in lower_lookup:
        return lower_lookup[lower]

    if lower in english_lookup and english_lookup[lower] in world_country_set:
        return english_lookup[lower]

    return value


def forward_normalize_countries(apps, schema_editor):
    from quotes.constants.country_aliases import COUNTRY_CODE_TO_NAME, COUNTRY_ENGLISH_TO_NAME
    from quotes.constants.countries import WORLD_COUNTRY_NAMES

    OriginLocation = apps.get_model("quotes", "OriginLocation")
    Quote = apps.get_model("quotes", "Quote")

    world_country_set = set(WORLD_COUNTRY_NAMES)
    lower_lookup = {country.lower(): country for country in WORLD_COUNTRY_NAMES}

    for location in OriginLocation.objects.all().iterator():
        normalized = _normalize_country(
            location.country,
            world_country_set,
            lower_lookup,
            COUNTRY_CODE_TO_NAME,
            COUNTRY_ENGLISH_TO_NAME,
        )
        if normalized != location.country:
            location.country = normalized
            location.save(update_fields=["country"])

    for quote in Quote.objects.all().iterator():
        updated_fields = []
        origin_normalized = _normalize_country(
            quote.origin_country,
            world_country_set,
            lower_lookup,
            COUNTRY_CODE_TO_NAME,
            COUNTRY_ENGLISH_TO_NAME,
        )
        destination_normalized = _normalize_country(
            quote.destination_country,
            world_country_set,
            lower_lookup,
            COUNTRY_CODE_TO_NAME,
            COUNTRY_ENGLISH_TO_NAME,
        )

        if origin_normalized != quote.origin_country:
            quote.origin_country = origin_normalized
            updated_fields.append("origin_country")
        if destination_normalized != quote.destination_country:
            quote.destination_country = destination_normalized
            updated_fields.append("destination_country")

        if updated_fields:
            quote.save(update_fields=updated_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0005_quote_destination_country_quote_destination_location_and_more"),
    ]

    operations = [
        migrations.RunPython(forward_normalize_countries, noop_reverse),
    ]
