# Generated by Django 5.2.11 on 2026-02-23 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def close_duplicate_open_rates(apps, schema_editor):
    LocationRate = apps.get_model("quotes", "LocationRate")

    location_ids = (
        LocationRate.objects.filter(is_active=True, effective_to__isnull=True)
        .values_list("location_id", flat=True)
        .distinct()
    )
    for location_id in location_ids:
        open_rates = list(
            LocationRate.objects.filter(
                location_id=location_id,
                is_active=True,
                effective_to__isnull=True,
            ).order_by("-effective_from", "-id")
        )
        if len(open_rates) <= 1:
            continue
        survivor = open_rates[0]
        for stale in open_rates[1:]:
            stale.effective_to = survivor.effective_from
            stale.is_active = False
            stale.save(update_fields=["effective_to", "is_active"])


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0006_normalize_country_values"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=80)),
                ("model_name", models.CharField(max_length=80)),
                ("object_id", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.RunPython(close_duplicate_open_rates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="locationrate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("effective_to__isnull", True), ("is_active", True)),
                fields=("location",),
                name="uniq_open_active_rate_per_location",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
