# Generated by Django 5.2.11 on 2026-02-23 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0007_auditlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_country", models.CharField(max_length=80)),
                ("destination_country", models.CharField(max_length=80)),
                (
                    "transport_type",
                    models.CharField(
                        choices=[("AIR", "Aereo"), ("SEA", "Maritimo")], max_length=10
                    ),
                ),
                ("rate_usd", models.DecimalField(decimal_places=4, max_digits=12)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_route_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "origin_country",
                    "destination_country",
                    "transport_type",
                    "-effective_from",
                    "-id",
                ],
            },
        ),
        migrations.AddField(
            model_name="quote",
            name="applied_route_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="quotes.routerate",
            ),
        ),
        migrations.AddConstraint(
            model_name="routerate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("effective_to__isnull", True), ("is_active", True)),
                fields=("origin_country", "destination_country", "transport_type"),
                name="uniq_open_active_route_rate",
            ),
        ),
    ]
