# Generated by Django 5.2.11 on 2026-02-23 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0008_routerate_quote_applied_route_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteRateTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_weight_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "max_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("rate_usd", models.DecimalField(decimal_places=4, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="quotes.routerate",
                    ),
                ),
            ],
            options={
                "ordering": ["route_rate_id", "min_weight_kg", "id"],
            },
        ),
        migrations.AddField(
            model_name="quote",
            name="applied_route_rate_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="quotes.routeratetier",
            ),
        ),
    ]
