# Generated by Django 5.2.11 on 2026-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0009_routeratetier_quote_applied_route_rate_tier"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action", "created_at"], name="quotes_audit_action_idx"),
        ),
        migrations.AddIndex(
            model_name="locationrate",
            index=models.Index(fields=["location", "is_active", "effective_from"], name="quotes_loc_rate_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="originlocation",
            index=models.Index(fields=["country", "location_type", "is_active"], name="quotes_origin_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["created_at"], name="quotes_created_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["transport_type", "created_at"], name="quotes_transport_created_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["user", "created_at"], name="quotes_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="routerate",
            index=models.Index(
                fields=["origin_country", "destination_country", "transport_type", "is_active"],
                name="quotes_route_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="routerate",
            index=models.Index(fields=["transport_type", "effective_from"], name="quotes_route_transport_idx"),
        ),
        migrations.AddIndex(
            model_name="routeratetier",
            index=models.Index(fields=["route_rate", "is_active", "min_weight_kg"], name="quotes_tier_lookup_idx"),
        ),
    ]
